services:
  db:
    image: postgres:17.5-alpine
    container_name: olist_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-olist_dw}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount initial scripts to run on first startup
      - ./docker/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-olist_dw}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pipeline:
   build:
    context: .
    dockerfile: docker/bronze-pipeline/dockerfile
   container_name: olist_pipeline
   depends_on:
     db:
       condition: service_healthy
   environment:
     POSTGRES_HOST: db
     POSTGRES_USER: ${POSTGRES_USER:-admin}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
     POSTGRES_DB: ${POSTGRES_DB:-olist_dw}
     POSTGRES_PORT: 5432
   volumes:
     # mount data to update files without rebuilding the image
     - ./Data:/app/Data
     - ./src:/app/src

volumes:
  postgres_data: